/**
 * Full-width profile editor form for the Agent Studio.
 * Extracted from AgentProfilesPanel with additions: live preview events, two-column layout.
 */

import { apiFetch } from "../shared/api.js";
import { LitElement, html, css, nothing } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import type { ProfileInfo, SkillInfo, FileInfo, ProfileFormData } from "./types.js";
import { EMPTY_FORM } from "./types.js";
import { getModelLabel } from "../shared/model-labels.js";
import "../components/InfoTooltip.js";

@customElement("profile-editor")
export class ProfileEditor extends LitElement {
	static override styles = css`
		:host {
			display: block;
		}
		.editor {
			display: flex;
			flex-direction: column;
			gap: 0.75rem;
		}
		.form-grid {
			display: grid;
			grid-template-columns: 1fr 1fr;
			gap: 0.75rem;
		}
		.form-full {
			grid-column: 1 / -1;
		}
		.form-field {
			display: flex;
			flex-direction: column;
			gap: 0.25rem;
		}
		label {
			font-size: 0.75rem;
			font-weight: 500;
			color: var(--muted-foreground, #6b7280);
		}
		input, select, textarea {
			padding: 0.5rem;
			border: 1px solid var(--border, #e5e7eb);
			border-radius: 0.375rem;
			font-size: 0.875rem;
			background: var(--background, #fff);
			color: var(--foreground, #111);
			font-family: inherit;
		}
		input:focus, select:focus, textarea:focus {
			outline: none;
			border-color: var(--primary, #2563eb);
			box-shadow: 0 0 0 2px color-mix(in srgb, var(--primary, #2563eb) 20%, transparent);
		}
		textarea {
			resize: vertical;
			min-height: 4rem;
		}
		textarea.system-prompt {
			min-height: 10rem;
			font-family: monospace;
			font-size: 0.8rem;
		}
		.icon-field {
			max-width: 80px;
		}
		.icon-input-wrapper {
			display: flex;
			align-items: center;
			gap: 0.25rem;
		}
		.icon-input-wrapper input {
			flex: 1;
			min-width: 0;
		}
		.icon-regen-btn {
			padding: 0.25rem 0.35rem;
			font-size: 0.8rem;
			line-height: 1;
			border: 1px solid var(--border, #e5e7eb);
			border-radius: 0.25rem;
			background: transparent;
			color: var(--muted-foreground, #6b7280);
			cursor: pointer;
			flex-shrink: 0;
		}
		.icon-regen-btn:hover:not(:disabled) {
			background: var(--muted, #f3f4f6);
			color: var(--foreground, #111);
		}
		.icon-regen-btn:disabled {
			opacity: 0.5;
			cursor: not-allowed;
		}
		.top-row {
			display: flex;
			gap: 0.75rem;
			align-items: flex-end;
		}
		.top-row .form-field {
			flex: 1;
		}
		.top-row .icon-field {
			flex: 0 0 80px;
		}
		.skill-checkboxes {
			display: flex;
			flex-wrap: wrap;
			gap: 0.5rem;
			max-height: 10rem;
			overflow-y: auto;
			padding: 0.5rem;
			border: 1px solid var(--border, #e5e7eb);
			border-radius: 0.375rem;
		}
		.skill-checkbox {
			display: flex;
			align-items: center;
			gap: 0.25rem;
			font-size: 0.8rem;
		}
		.skill-checkbox input[type="checkbox"] {
			margin: 0;
			padding: 0;
		}
		.skill-scope {
			font-size: 0.6rem;
			color: var(--muted-foreground, #6b7280);
		}
		.form-actions {
			display: flex;
			gap: 0.5rem;
			justify-content: flex-end;
			padding-top: 0.5rem;
			border-top: 1px solid var(--border, #e5e7eb);
		}
		button {
			padding: 0.5rem 1rem;
			border: none;
			border-radius: 0.375rem;
			font-size: 0.875rem;
			cursor: pointer;
			font-weight: 500;
		}
		.btn-primary {
			background: var(--primary, #2563eb);
			color: white;
		}
		.btn-primary:hover {
			opacity: 0.9;
		}
		.btn-primary:disabled {
			opacity: 0.5;
			cursor: not-allowed;
		}
		.btn-secondary {
			background: transparent;
			color: var(--foreground, #111);
			border: 1px solid var(--border, #e5e7eb);
		}
		.btn-secondary:hover {
			background: var(--muted, #f3f4f6);
		}
		.status {
			font-size: 0.875rem;
			padding: 0.5rem;
			border-radius: 0.375rem;
		}
		.status-success { background: #dcfce7; color: #166534; }
		.status-error { background: #fef2f2; color: #991b1b; }
		.advanced-toggle {
			display: flex;
			align-items: center;
			gap: 0.5rem;
			padding: 0.5rem 0;
			border-top: 1px solid var(--border, #e5e7eb);
			cursor: pointer;
			font-size: 0.8rem;
			color: var(--muted-foreground, #6b7280);
			user-select: none;
		}
		.advanced-toggle:hover {
			color: var(--foreground, #111);
		}
		.label-with-tooltip {
			display: inline-flex;
			align-items: center;
			gap: 0.25rem;
		}
	`;

	@property({ type: Object })
	profile: ProfileInfo | null = null;

	@property({ type: Function })
	getToken: (() => string | null) | undefined;

	@property({ type: String })
	userRole: string = "member";

	@property({ type: Array })
	availableSkills: SkillInfo[] = [];

	@property({ type: Array })
	availableFiles: FileInfo[] = [];

	@property({ type: Object })
	initialForm: ProfileFormData | null = null;

	@state() private form: ProfileFormData = { ...EMPTY_FORM };
	@state() private saving = false;
	@state() private statusMessage = "";
	@state() private statusType: "success" | "error" = "success";
	@state() private iconAutoGenerated = false;
	@state() private generatingIcon = false;
	@state() private advancedMode = false;

	private _previewTimer: ReturnType<typeof setTimeout> | undefined;
	private _dismissTimer: ReturnType<typeof setTimeout> | undefined;
	private _iconGenTimer: ReturnType<typeof setTimeout> | undefined;
	private _keyHandler = (e: KeyboardEvent) => this._handleKeyDown(e);

	override connectedCallback() {
		super.connectedCallback();
		window.addEventListener("keydown", this._keyHandler);
		if (this.profile) {
			this.form = {
				name: this.profile.name,
				description: this.profile.description || "",
				icon: this.profile.icon || "",
				scope: this.profile.scope,
				system_prompt: this.profile.system_prompt,
				prompt_mode: this.profile.prompt_mode,
				skill_ids: this.profile.skill_ids || [],
				file_ids: this.profile.file_ids || [],
				model_id: this.profile.model_id || "",
				provider: this.profile.provider || "",
				starter_message: this.profile.starter_message || "",
				suggested_prompts: this.profile.suggested_prompts || [],
			};
		} else if (this.initialForm) {
			this.form = { ...this.initialForm };
		}
		this._emitPreview();
	}

	override disconnectedCallback() {
		super.disconnectedCallback();
		clearTimeout(this._previewTimer);
		clearTimeout(this._dismissTimer);
		clearTimeout(this._iconGenTimer);
		window.removeEventListener("keydown", this._keyHandler);
	}

	private _handleKeyDown(e: KeyboardEvent) {
		if (e.key === "Escape") {
			this.dispatchEvent(new CustomEvent("cancel", { bubbles: true, composed: true }));
		}
		if ((e.metaKey || e.ctrlKey) && e.key === "s") {
			e.preventDefault();
			if (!this.saving && this.form.name && this.form.system_prompt) {
				this._handleSave();
			}
		}
	}

	private _updateForm(partial: Partial<ProfileFormData>) {
		this.form = { ...this.form, ...partial };
		this._emitPreviewDebounced();
	}

	private _emitPreviewDebounced() {
		clearTimeout(this._previewTimer);
		this._previewTimer = setTimeout(() => this._emitPreview(), 150);
	}

	private _emitPreview() {
		this.dispatchEvent(new CustomEvent("preview-change", {
			detail: { form: { ...this.form } },
			bubbles: true,
			composed: true,
		}));
	}

	private _toggleSkill(skillId: string) {
		const ids = new Set(this.form.skill_ids);
		if (ids.has(skillId)) ids.delete(skillId);
		else ids.add(skillId);
		this._updateForm({ skill_ids: [...ids] });
	}

	private _toggleFile(fileId: string) {
		const ids = new Set(this.form.file_ids);
		if (ids.has(fileId)) ids.delete(fileId);
		else ids.add(fileId);
		this._updateForm({ file_ids: [...ids] });
	}

	private _updateSuggestedPrompts(value: string) {
		const prompts = value.split("\n").map(s => s.trim()).filter(Boolean);
		this._updateForm({ suggested_prompts: prompts });
	}

	private _onNameInput(value: string) {
		this._updateForm({ name: value });
		if (value && (this.form.icon === "" || this.iconAutoGenerated)) {
			clearTimeout(this._iconGenTimer);
			this._iconGenTimer = setTimeout(() => this._generateIcon(), 500);
		}
	}

	private _onIconInput(value: string) {
		this.iconAutoGenerated = false;
		this._updateForm({ icon: value });
	}

	private async _generateIcon() {
		if (!this.form.name) return;
		this.generatingIcon = true;
		try {
			const result = await this._fetchApi("/api/agent-profiles/generate-icon", {
				method: "POST",
				body: JSON.stringify({
					name: this.form.name,
					description: this.form.description || undefined,
					provider: this.form.provider || undefined,
					model: this.form.model_id || undefined,
				}),
			});
			if (result.success && result.data?.icon) {
				this._updateForm({ icon: result.data.icon });
				this.iconAutoGenerated = true;
			}
		} catch {
			// Silently fail — user can still type an icon manually
		} finally {
			this.generatingIcon = false;
		}
	}

	private _fetchApi = (url: string, options?: RequestInit) => apiFetch(url, options, this.getToken);

	private async _handleSave() {
		// In basic mode, auto-generate a system prompt if not provided
		if (!this.advancedMode && !this.form.system_prompt && this.form.name) {
			const desc = this.form.description ? ` ${this.form.description}.` : "";
			this._updateForm({
				system_prompt: `You are ${this.form.name}, a helpful AI assistant.${desc} Be clear, concise, and helpful in your responses.`,
			});
		}

		if (!this.form.name || !this.form.system_prompt) {
			this.statusMessage = "Name is required" + (this.advancedMode ? " and system prompt is required" : "");
			this.statusType = "error";
			return;
		}

		this.saving = true;
		this.statusMessage = "";

		try {
			const body = {
				...this.form,
				skill_ids: this.form.skill_ids.length > 0 ? this.form.skill_ids : null,
				file_ids: this.form.file_ids.length > 0 ? this.form.file_ids : null,
				model_id: this.form.model_id || null,
				provider: this.form.provider || null,
				description: this.form.description || null,
				icon: this.form.icon || null,
				starter_message: this.form.starter_message || null,
				suggested_prompts: this.form.suggested_prompts.length > 0 ? this.form.suggested_prompts : null,
			};

			let result;
			if (this.profile) {
				result = await this._fetchApi(`/api/agent-profiles/${this.profile.id}`, {
					method: "PUT",
					body: JSON.stringify(body),
				});
			} else {
				result = await this._fetchApi("/api/agent-profiles", {
					method: "POST",
					body: JSON.stringify(body),
				});
			}

			if (result.success) {
				this.statusMessage = this.profile
					? `Profile "${this.form.name}" updated.`
					: `Profile "${this.form.name}" created.`;
				this.statusType = "success";
				clearTimeout(this._dismissTimer);
				this._dismissTimer = setTimeout(() => { this.statusMessage = ""; }, 3000);
				this.dispatchEvent(new CustomEvent("save", {
					detail: { profile: result.data?.profile || result.data },
					bubbles: true,
					composed: true,
				}));
			} else {
				this.statusMessage = result.error || "Save failed";
				this.statusType = "error";
			}
		} catch {
			this.statusMessage = "Network error";
			this.statusType = "error";
		} finally {
			this.saving = false;
		}
	}

	override render() {
		const isAdmin = this.userRole === "admin";

		return html`
			<div class="editor">
				${this.statusMessage ? html`
					<div class="status ${this.statusType === "success" ? "status-success" : "status-error"}">
						${this.statusMessage}
					</div>
				` : nothing}

				<!-- Row 1: Icon + Name + Scope (admin only) -->
				<div class="top-row">
					<div class="form-field icon-field">
						<label>Icon</label>
						<div class="icon-input-wrapper">
							<input
								type="text"
								placeholder=${this.generatingIcon ? "..." : "e.g. emoji"}
								maxlength="4"
								.value=${this.form.icon}
								@input=${(e: Event) => this._onIconInput((e.target as HTMLInputElement).value)}
							/>
							${this.form.name ? html`
								<button
									class="icon-regen-btn"
									title="Generate icon"
									?disabled=${this.generatingIcon}
									@click=${() => this._generateIcon()}
								>${this.generatingIcon ? "..." : "\u{21BB}"}</button>
							` : nothing}
						</div>
					</div>
					<div class="form-field">
						<label>Name *</label>
						<input
							type="text"
							placeholder="e.g. Finance Agent"
							maxlength="100"
							.value=${this.form.name}
							@input=${(e: Event) => this._onNameInput((e.target as HTMLInputElement).value)}
						/>
					</div>
					${isAdmin ? html`
						<div class="form-field" style="max-width: 140px;">
							<label class="label-with-tooltip">
								Scope
								<info-tooltip text="Platform: visible to all users. Team: visible to your team. Personal: only you."></info-tooltip>
							</label>
							<select
								.value=${this.form.scope}
								@change=${(e: Event) => this._updateForm({ scope: (e.target as HTMLSelectElement).value })}
								?disabled=${!!this.profile}
							>
								<option value="user">Personal</option>
								<option value="team">Team</option>
								<option value="platform">Platform</option>
							</select>
						</div>
					` : nothing}
				</div>

				<!-- Description -->
				<div class="form-field">
					<label>Description</label>
					<input
						type="text"
						placeholder="Brief description of what this agent does"
						.value=${this.form.description}
						@input=${(e: Event) => this._updateForm({ description: (e.target as HTMLInputElement).value })}
					/>
				</div>

				<!-- Starter Message (basic mode) -->
				<div class="form-field">
					<label>Starter Message (optional — shown when chat starts)</label>
					<textarea
						placeholder="Hi! I'm the Finance Agent. I can help you with..."
						.value=${this.form.starter_message}
						@input=${(e: Event) => this._updateForm({ starter_message: (e.target as HTMLTextAreaElement).value })}
					></textarea>
				</div>

				<!-- Suggested Prompts (basic mode) -->
				<div class="form-field">
					<label>Suggested Prompts (one per line, optional)</label>
					<textarea
						placeholder="Check Q4 revenue&#10;Run expense report&#10;Compare budgets"
						.value=${this.form.suggested_prompts.join("\n")}
						@input=${(e: Event) => this._updateSuggestedPrompts((e.target as HTMLTextAreaElement).value)}
					></textarea>
				</div>

				<!-- Advanced toggle -->
				<div class="advanced-toggle" @click=${() => { this.advancedMode = !this.advancedMode; }}>
					<span>${this.advancedMode ? "\u25BC" : "\u25B6"}</span>
					<span>Advanced settings</span>
				</div>

				${this.advancedMode ? html`
					<!-- System Prompt -->
					<div class="form-field">
						<label class="label-with-tooltip">
							System Prompt ${this.advancedMode ? "*" : ""}
							<info-tooltip text="Instructions that define the agent's behavior. In basic mode, this is auto-generated from the name and description."></info-tooltip>
							<select
								style="display: inline; margin-left: 0.5rem; font-size: 0.7rem;"
								.value=${this.form.prompt_mode}
								@change=${(e: Event) => this._updateForm({ prompt_mode: (e.target as HTMLSelectElement).value })}
							>
								<option value="replace">Replace default prompt</option>
								<option value="append">Append to default prompt</option>
							</select>
						</label>
						<textarea
							class="system-prompt"
							placeholder="You are a specialized agent that..."
							.value=${this.form.system_prompt}
							@input=${(e: Event) => this._updateForm({ system_prompt: (e.target as HTMLTextAreaElement).value })}
						></textarea>
					</div>

					<!-- Provider + Model -->
					<div class="form-grid">
						<div class="form-field">
							<label class="label-with-tooltip">
								Provider
								<info-tooltip text="Which AI provider to use. Leave as Default to use your team's configured provider."></info-tooltip>
							</label>
							<select
								.value=${this.form.provider}
								@change=${(e: Event) => this._updateForm({ provider: (e.target as HTMLSelectElement).value })}
							>
								<option value="">Default</option>
								<option value="anthropic">Anthropic</option>
								<option value="openai">OpenAI</option>
								<option value="google">Google</option>
							</select>
						</div>
						<div class="form-field">
							<label class="label-with-tooltip">
								Model
								<info-tooltip text="Specific AI model to use. Leave empty to use the default model for the selected provider."></info-tooltip>
							</label>
							<input
								type="text"
								placeholder="e.g. claude-sonnet-4-20250514"
								.value=${this.form.model_id}
								@input=${(e: Event) => this._updateForm({ model_id: (e.target as HTMLInputElement).value })}
							/>
						</div>
					</div>

					<!-- Skills -->
					${this.availableSkills.length > 0 ? html`
						<div class="form-field">
							<label>Agent Tools (select which tools this agent can use)</label>
							<div class="skill-checkboxes">
								${this.availableSkills.map(skill => html`
									<label class="skill-checkbox">
										<input
											type="checkbox"
											.checked=${this.form.skill_ids.includes(skill.id)}
											@change=${() => this._toggleSkill(skill.id)}
										/>
										<span>${skill.name}</span>
										<span class="skill-scope">(${skill.scope})</span>
									</label>
								`)}
							</div>
						</div>
					` : nothing}

					<!-- Files -->
					${this.availableFiles.length > 0 ? html`
						<div class="form-field">
							<label>Files (select files to load into the agent session)</label>
							<div class="skill-checkboxes">
								${this.availableFiles.map(file => html`
									<label class="skill-checkbox">
										<input
											type="checkbox"
											.checked=${this.form.file_ids.includes(file.id)}
											@change=${() => this._toggleFile(file.id)}
										/>
										<span>${file.filename}</span>
									</label>
								`)}
							</div>
						</div>
					` : nothing}
				` : nothing}

				<!-- Actions -->
				<div class="form-actions">
					<button class="btn-secondary" @click=${() => this.dispatchEvent(new CustomEvent("cancel", { bubbles: true, composed: true }))}>
						Cancel
					</button>
					<button
						class="btn-primary"
						?disabled=${this.saving || !this.form.name}
						@click=${() => this._handleSave()}
					>
						${this.saving ? "Saving..." : (this.profile ? "Update" : "Create")}
					</button>
				</div>
			</div>
		`;
	}
}
